title: Geospatial Data Science And Machine Learning
id: chapter7
sections:
  - title: Geospatial Clustering With Apache Sedona (DBScan)
    id: geospatial-clustering-with-apache-sedona
    images:
      - image: sedona
        open-webui:
          path: http://localhost:8888/lab/workspaces/auto-R/tree/ClusteringWithApacheSedona.ipynb
        volumes:
          - chapter7/ClusteringWithApacheSedona.ipynb:/opt/workspace/ClusteringWithApacheSedona.ipynb
          - source_data/density_points:/opt/workspace/source_data/density_points
  - title: Outlier Detection (Local Outlier Factor (LOF))
    id: outlier-detection
    images:
      - image: sedona
        open-webui:
          path: http://localhost:8888/lab/workspaces/auto-R/tree/OutlierDetection.ipynb
        volumes:
          - chapter7/OutlierDetection.ipynb:/opt/workspace/OutlierDetection.ipynb
          - source_data/density_points:/opt/workspace/source_data/density_points
  - title: Hot Spot analysis (Local Getis-Ord Gi(*))
    id: hot-spot-analysis
    images:
      - image: sedona
        open-webui:
          path: http://localhost:8888/lab/workspaces/auto-R/tree/HotSpotAnalysis.ipynb
        volumes:
          - chapter7/HotSpotAnalysis.ipynb:/opt/workspace/HotSpotAnalysis.ipynb
      - image: minio
        volumes:
          - scripts/copy_minio.sh:/app/scripts/copy_minio.sh
          - source_data/hot_spot:/app/sources/hot_spot
  - title: AutoCorrelation (MoranI)
    id: autocorrelation
    images:
      - image: sedona
        open-webui:
          path: http://localhost:8888/lab/workspaces/auto-R/tree/AutoCorrelation.ipynb
        volumes:
          - chapter7/AutoCorrelation.ipynb:/opt/workspace/AutoCorrelation.ipynb
        browser-path: chapter7/AutoCorrelation.ipynb
  - title: Classification, Segmentation, and Object Detection from Raster
    id: classification-segmentation-and-object-detection-from-raster
    images:
      - image: sedona-ai
        open-webui:
          path: http://localhost:8888/lab/workspaces/auto-R/tree/RasterSegmentation.ipynb
        volumes:
          - chapter7/sql.py:/home/ubuntu/sedona-ai/sql.py
          - chapter7/RasterSegmentation.ipynb:/home/ubuntu/sedona-ai/RasterSegmentation.ipynb
  - title: Create Geospatial Machine Learning models with MLLib
    id: create-geospatial-machine-learning-models-with-mllib
    images:
      - image: sedona
        open-webui:
          path: http://localhost:8888/lab/workspaces/auto-R/tree/MLLib.ipynb
        volumes:
          - chapter7/MLLib.ipynb:/opt/workspace/MLLib.ipynb
      - image: ors
        volumes:
          - chapter7/ors/graphs:/home/ors/graphs
  - title: Analysing the accidents in Germany
    id: analysing-the-accidents-in-germany
    images:
      - image: sedona
        open-webui:
          path: http://localhost:8888/lab/workspaces/auto-R/tree/AccidentAnalysis.ipynb
        volumes:
          - chapter7/AccidentAnalysis.ipynb:/opt/workspace/AccidentAnalysis.ipynb
          - chapter7/slope.py:/opt/workspace/slope.py
