title: Apache Sedona And The PyData Ecosystem
id: chapter6
sections:
  - title: Manipulating Geospatial Vector Data
    id: manipulating-geospatial-vector-data
    images:
      - image: sedona
        volumes:
          - chapter6/ManipulatingGeospatialVectorData.ipynb:/opt/workspace/ManipulatingGeospatialVectorData.ipynb
        open-webui:
          path: http://localhost:8888/lab/workspaces/auto-R/tree/ManipulatingGeospatialVectorData.ipynb
      - image: minio
        volumes:
          - scripts/copy_minio.sh:/app/scripts/copy_minio.sh
          - source_data/transportation_barcelona:/app/sources/transportation
  - title: Raster Data Tools
    id: raster-data-tools
    images:
      - image: sedona
        volumes:
          - chapter6/RasterDataTools.ipynb:/opt/workspace/RasterDataTools.ipynb
          - chapter6/ID73_S20_W70_RP10_depth.tif:/opt/workspace/ID73_S20_W70_RP10_depth.tif
        open-webui:
          path: http://localhost:8888/lab/workspaces/auto-R/tree/RasterDataTools.ipynb
  - title: "Scheduling your geospatial code"
    id: scheduling-your-geospatial-code
    images:
      - image: airflow
        volumes:
          - chapter6/dags/:/opt/airflow/dags/chapter6
        open-webui:
          path: http://localhost:8080
      - image: minio
        volumes:
          - source_data/transportation:/app/sources/transportation
          - scripts/copy_minio.sh:/app/scripts/copy_minio.sh
  - title: Transforming your Geospatial Data with dbt
    id: transforming-your-geospatial-data-with-dbt
    images:
      - image: sedonadbt
        volumes:
          - chapter6/geospatialdbt:/opt/workspace
        open-terminal: true
      - image: thriftserver
  - title: Visualizing Geospatial Data
    id: visualizing-geospatial-data
    images:
      - image: sedona
        volumes:
          - chapter6/VectorGeospatialVisualization.ipynb:/opt/workspace/VectorGeospatialVisualization.ipynb
          - chapter6/kepler_map_config.json:/opt/workspace/kepler_map_config.json
        open-webui:
          path: http://localhost:8888/lab/workspaces/auto-R/tree/VectorGeospatialVisualization.ipynb
  - title: Extra Materials - Prefect
    id: extra-materials-prefect
    images:
      - image: prefect
        volumes:
          - chapter6/prefect_flows:/opt/workspace