title: Raster Data Analysis
id: chapter5
sections:
  - title: The Raster Data Model
    id: the-raster-data-model
    images:
      - image: sedona
        open-webui:
          path: http://localhost:8888/lab/workspaces/auto-R/tree/RasterModel.ipynb
        volumes:
          - chapter5/RasterModel.ipynb:/opt/workspace/RasterModel.ipynb
  - title: Raster SQL and Raster Data Manipulation
    id: raster-sql-and-raster-data-manipulation
    images:
      - image: sedona
        open-webui:
          path: http://localhost:8888/lab/workspaces/auto-R/tree/Raster SQL and Raster Data Manipulation.ipynb
        volumes:
          - chapter5/Raster SQL and Raster Data Manipulation.ipynb:/opt/workspace/Raster SQL and Raster Data Manipulation.ipynb
  - title: Zonal Statistics
    id: zonal-statistics
    images:
      - image: sedona
        open-webui:
          path: http://localhost:8888/lab/workspaces/auto-R/tree/Zonal Statistics.ipynb
        volumes:
          - chapter5/images:/opt/workspace/images
          - chapter5/Zonal Statistics.ipynb:/opt/workspace/Zonal Statistics.ipynb
          - chapter5/zone_stats_config.json:/opt/workspace/zone_stats_config.json
  - title: Map Algebra
    id: map-algebra
    images:
      - image: sedona
        open-webui:
          path: http://localhost:8888/lab/workspaces/auto-R/tree/MapAlgebra.ipynb
        volumes:
          - chapter5/MapAlgebra.ipynb:/opt/workspace/MapAlgebra.ipynb
  - title: Joining raster data with vector data
    id: joining-raster-data-with-vector-data
    images:
      - image: sedona
        open-webui:
          path: http://localhost:8888/lab/workspaces/auto-R/tree/RasterJoin.ipynb
        volumes:
          - chapter5/RasterJoin.ipynb:/opt/workspace/RasterJoin.ipynb
  - title: Hands-On Use Case\:\ Insurance Risk Modeling
    id: hands-on-use-case-insurance-risk-modeling
    images:
      - image: sedona
        open-webui:
          path: http://localhost:8888/lab/workspaces/auto-R/tree/Use Case Insurance Risk Modeling.ipynb
        volumes:
          - chapter5/Use Case Insurance Risk Modeling.ipynb:/opt/workspace/Use Case Insurance Risk Modeling.ipynb
          - chapter5/warsaw_viz_config.json:/opt/workspace/warsaw_viz_config.json
