title: Working With Geospatial Data At Scale\:\ Loading Data In Apache Sedona
id: chapter3

sections:
  - title: Loading Vector Data Formats
    id: loading-vector-data-formats
    images:
      - image: sedona
        open-webui:
          path: http://localhost:8888/lab/workspaces/auto-R/tree/LoadingVectorDataFormats.ipynb
        volumes:
          - chapter3/LoadingVectorDataFormats.ipynb:/opt/workspace/LoadingVectorDataFormats.ipynb
  - title: Introduction To Raster Data Formats (GeoTif)
    id: introduction-to-raster-data-formats-geotif
    images:
      - image: sedona
        open-webui:
          path: http://localhost:8888/lab/workspaces/auto-R/tree/LoadingRasterData.ipynb
        volumes:
          - chapter3/LoadingRasterData.ipynb:/opt/workspace/LoadingRasterData.ipynb
  - title: Loading Data From Databases
    id: loading-data-from-databases
    images:
      - image: sedona
        open-webui:
          path: http://localhost:8888/lab/workspaces/auto-R/tree/ReadingFromPostgreSQL.ipynb
        volumes:
          - chapter3/ReadingFromPostgreSQL.ipynb:/opt/workspace/ReadingFromPostgreSQL.ipynb
      - image: postgis
      - image: mysql
      - image: mongo
      - image: debezium
      - image: kafka
      - image: minio
  - title: "Hands-On Use Case: NYC Taxi Data Analysis"
    id: hands-on-use-case-nyc-taxi-data-analysis
    images:
      - image: sedona
        open-webui:
          path: http://localhost:8888/lab/workspaces/auto-R/tree/NewYorkTaxiAnalysis.ipynb
        volumes:
          - chapter3/NewYorkTaxiAnalysis.ipynb:/opt/workspace/NewYorkTaxiAnalysis.ipynb
          - chapter3/popular_routes_config.json:/opt/workspace/popular_routes_config.json
          - chapter3/populardropoff_config.json:/opt/workspace/populardropoff_config.json
          - chapter3/analysis_area.json:/opt/workspace/analysis_area.json
