# spark executor settings
spark.driver.memory 5g
spark.executor.memory 5g

# sedona bucket
spark.hadoop.fs.s3a.bucket.apache-sedona-book.aws.credentials.provider org.apache.hadoop.fs.s3a.AnonymousAWSCredentialsProvider

# iceberg properties
spark.hadoop.fs.s3a.impl org.apache.hadoop.fs.s3a.S3AFileSystem
spark.sql.catalog.sedona_catalog org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.sedona_catalog.warehouse s3a://apache-sedona-book-local/data
spark.sql.catalog.sedona_catalog.type jdbc
spark.sql.catalog.sedona_catalog.uri jdbc:postgresql://postgres:5432/sedona
spark.sql.catalog.sedona_catalog.jdbc.verifyServerCertificate true
spark.sql.catalog.sedona_catalog.jdbc.useSSL true
spark.sql.catalog.sedona_catalog.jdbc.user sedona
spark.sql.catalog.sedona_catalog.jdbc.password sedona

# minio bucket
spark.hadoop.fs.s3a.bucket.apache-sedona-book-local.aws.credentials.provider org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
spark.hadoop.fs.s3a.bucket.apache-sedona-book-local.access.key sedona
spark.hadoop.fs.s3a.bucket.apache-sedona-book-local.secret.key sedona_password
spark.hadoop.fs.s3a.bucket.apache-sedona-book-local.path.style.access true
spark.hadoop.fs.s3a.bucket.apache-sedona-book-local.endpoint http://minio:9000


# unlock sedona
spark.sql.extensions org.apache.sedona.viz.sql.SedonaVizExtensions,org.apache.sedona.sql.SedonaSqlExtensions
